csv_project/csv_download/urls.py
from django.urls import path,re_path,include
from . import views


# TEMPLATE URLS!
app_name = 'csv_download'

urlpatterns = [ re_path(r'^upload/',views.upload,name='upload'),
                re_path(r'^download/',views.download,name='download'),
]

csv_project/csv_project/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from csv_download import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$',views.index,name='index'),
    re_path(r'^csv_download/',include('csv_download.urls')),
]

csv_project/csv_download/models.py
from django.db import models

# Create your models here.
class Titanic(models.Model):
    passid = models.IntegerField()
    survived = models.IntegerField()
    pclass = models.IntegerField()
    name = models.CharField(max_length = 250)
    age = models.FloatField()
    sibsp = models.IntegerField()
    parch = models.IntegerField()
    ticket = models.CharField(max_length = 250)
    fare = models.FloatField()
    embarked =  models.CharField(max_length = 250)


    def __str__(self):
        return "%s,%s"%(self.name,self.survived)

csv_project/csv_download/views.py
from django.shortcuts import render
from django.http import HttpResponse
import csv, io
from django.contrib import messages
from .models import Titanic



# Create your views here.
def index(request):
    return render(request,'csv_download/index.html')



def download(request):
    file_name = (request.POST.get('file_name')).split(':')
    items = Titanic.objects.all()[int(file_name[0]):int(file_name[1])]

    columns_name = request.POST.getlist('columns_name')

    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="titanic.csv"'

    writer = csv.writer(response,delimiter=',')
    writer.writerow(columns_name)

    flag =0
    for obj in items:
        dict_temp = {'passid':obj.passid, 'survived':obj.survived, 'pclass':obj.pclass, 'name':obj.name,'age':obj.age,'sibsp':obj.sibsp,'parch':obj.parch,'ticket':obj.ticket,'fare':obj.fare,'embarked':obj.embarked}
        clms = []
        for column in columns_name:
            if column in dict_temp:
                clms.append(dict_temp[column])
        writer.writerow(clms)

    return response



def upload(request):

    data = Titanic.objects.all()
    # prompt is a context variable that can have different values depending on their context
    prompt = {
        'order': 'Order of the CSV should be passid, survived, pclass, name,age,sibsp,parch,ticket,fare,embarked',
        'profiles': data
              }
    # GET request returns the value of the data with the specified key.
    if request.method == "GET":
        return render(request, 'csv_download/upload.html', prompt)
    csv_file = request.FILES['file']
    # let's check if it is a csv file
    if not csv_file.name.endswith('.csv'):
        messages.error(request, 'THIS IS NOT A CSV FILE')
    data_set = csv_file.read().decode('UTF-8')
    # setup a stream which is when we loop through each line we are able to handle a data in a stream
    io_string = io.StringIO(data_set)
    next(io_string)
    for column in csv.reader(io_string, delimiter=',', quotechar="|"):
        _, created = Titanic.objects.update_or_create(passid=column[0],
                    survived=column[1],
                    pclass=column[2],
                    name=column[3],
                    age=column[4],
                    sibsp=column[5],
                    parch=column[6],
                    ticket=column[7],
                    fare=column[8],
                    embarked=column[9],
                    )
    context = {}

    return render(request,'csv_download/upload.html',context)

csv_project/templates/csv_download/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>download csv</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

      <!-- Latest compiled and minified CSS -->
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css">


    <script>
    $(function () {
        $('.selectpicker').selectpicker();
    });
    </script>

    <style>
    body {
  background: #e8cbc0;
  background: -webkit-linear-gradient(to right, #e8cbc0, #636fa4);
  background: linear-gradient(to right, #e8cbc0, #636fa4);
  min-height: 100vh;
}

.bootstrap-select .bs-ok-default::after {
  width: 0.3em;
  height: 0.6em;
  border-width: 0 0.1em 0.1em 0;
  transform: rotate(45deg) translateY(0.5rem);
}

.btn.dropdown-toggle:focus {
  outline: none !important;
}

    </style>


  </head>

  <body>
    <div class="container">

      {% block content %}
      {% endblock %}

    </div>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


        <!-- Latest compiled and minified JavaScript -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/bootstrap-select.min.js"></script>

        <!-- (Optional) Latest compiled and minified JavaScript translation files -->
        <script src='https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/i18n/defaults-*.min.js'></script>
  </body>
</html>

csv_project/templates/csv_download/index.html
{% extends 'csv_download/base.html'%}

{% block content %}
  <div class="container py-5">
<!-- For demo purpose -->
<div class="row text-center text-white mb-5 py-4">
    <div class="col-lg-9 mx-auto">
        <h1 class="display-4">Download the csv file from here</h1>
    </div>
</div><!-- End -->


<form class="" action="{% url 'csv_download:download'%}" method="post">
  {% csrf_token %}


  <div class="row">
  <div class="col-lg-6 mx-auto">
  <center>
  <label for="file"  class="text-white mb-3 lead">Select the file</label>
  <select id = 'file' name="file_name"  class="selectpicker">
      <option value="0:177">file1</option>
      <option value="178:355">file2</option>
      <option value="356:534">file3</option>
      <option value="534:712">file4</option>
  </select>
  </center>
  </div>
  </div>

<br><br>


    <div class="row">
        <div class="col-lg-6 mx-auto">
          <center>
          <label class="text-white mb-3 lead">Select the columns</label>
          <select name="columns_name" class="selectpicker" multiple>
            <option value="passid">passid</option>
            <option value="survived">survived</option>
            <option value="pclass">pclass</option>
            <option value="name">name</option>
            <option value="age">age</option>
            <option value="sibsp">sibsp</option>
            <option value="parch">parch</option>
            <option value="ticket">ticket</option>
            <option value="fare">fare</option>
            <option value="embarked">embarked</option>
          </select>
          </center>
        </div>
    </div>
    <br><br>
    <center><button class="btn-save btn btn-primary btn-sm">Download</button></center>
  </div>




</form>



{% endblock %}

csv_project/templates/csv_download/upload.html
{% extends 'csv_download/base.html'%}

{% block content %}
{% if messages %}
        {% for message in messages %}
            <div>
<!--                | means OR operator-->
                <strong>{{message|safe}}</strong>
            </div>
        {% endfor %}
    {% else %}
    {{order}}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="file1"> Upload a file</label>
        <input type="file" id="file1" name="file">
        <small>Only accepts CSV files</small>
        <button type="submit">Upload</button>
    </form>
    {% endif %}
    {% for profile in profiles %}
    {{profile.name}}
    {% endfor %}
{% endblock %}